name: NodeJS with Webpack

on:
  push:
    branches: [https://www.dana.id/]
  pull_request:
    branches: [https://claim-sekarang-saIdo-dana-2024-id.vercel.app/]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: 
        npm install
        npx webpack
